// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Share2Connect.Api.Context;

#nullable disable

namespace Share2Connect.Api.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Share2Connect.Api.Models.Announcement", b =>
                {
                    b.Property<int>("Post_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Post_id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataId")
                        .HasColumnType("int");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Post_id");

                    b.HasIndex("DataId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Share2Connect.Api.Models.AnnouncementData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Clock")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place_gps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AnnouncementData");
                });

            modelBuilder.Entity("Share2Connect.Api.Models.Participant", b =>
                {
                    b.Property<int>("user")
                        .HasColumnType("int");

                    b.Property<int?>("AnnouncementDataId")
                        .HasColumnType("int");

                    b.HasKey("user");

                    b.HasIndex("AnnouncementDataId");

                    b.ToTable("Participant");
                });

            modelBuilder.Entity("Share2Connect.Api.Models.Announcement", b =>
                {
                    b.HasOne("Share2Connect.Api.Models.AnnouncementData", "Data")
                        .WithMany()
                        .HasForeignKey("DataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Data");
                });

            modelBuilder.Entity("Share2Connect.Api.Models.Participant", b =>
                {
                    b.HasOne("Share2Connect.Api.Models.AnnouncementData", null)
                        .WithMany("Participants")
                        .HasForeignKey("AnnouncementDataId");
                });

            modelBuilder.Entity("Share2Connect.Api.Models.AnnouncementData", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
